apiVersion: tekton.dev/v1
kind: Task
metadata:
  creationTimestamp: "2023-11-23T08:29:20Z"
  generation: 1
  name: cleanup
  namespace: krausj02-dev
  resourceVersion: "3434389657"
  uid: 1b17e40b-3c71-4d7b-b6c6-e93e19d65c81
spec:
  steps:
  - computeResources: {}
    image: alpine:latest
    name: cleanup
    script: |
      #!/usr/bin/env sh
      rm -rf $(workspaces.source.path)/*
  workspaces:
  - name: source
