apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-22T13:16:27Z"
  name: java-app
  namespace: krausj02-dev
  resourceVersion: "3431590532"
  uid: 17b86ebd-bb8a-4a5c-aa0e-1ffe212219d8
spec:
  clusterIP: 172.30.10.36
  clusterIPs:
  - 172.30.10.36
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
