apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"java-app:latest","namespace":"krausj02-dev"},"fieldPath":"spec.template.spec.containers[?(@.name==\"container\")].image","pause":"false"}]'
  creationTimestamp: "2023-11-22T13:13:58Z"
  generation: 16
  name: java-app
  namespace: krausj02-dev
  resourceVersion: "3435124225"
  uid: baff57ad-27e6-4a69-9711-12d4f88d5f14
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: java-app
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-app
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/krausj02-dev/java-app@sha256:3e32113f9b2630bcf41f8957b3f42c46d41db55b9a25c354bd0d8f9aab99d320
        imagePullPolicy: IfNotPresent
        name: container
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-11-22T14:10:32Z"
    lastUpdateTime: "2023-11-22T14:10:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-22T13:13:58Z"
    lastUpdateTime: "2023-11-23T13:14:03Z"
    message: ReplicaSet "java-app-647cf88cf8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 16
