apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-11-23T09:49:57Z"
  generation: 2
  name: nginx-deployment
  namespace: krausj02-dev
  resourceVersion: "3435130203"
  uid: 4159657d-2273-4273-9aa5-2fcdacf82a5c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - command:
        - nginx
        - -g
        - daemon off;
        image: registry.access.redhat.com/ubi8/nginx-120
        imagePullPolicy: Always
        name: nginx-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: dependency-security-report
        name: config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-11-23T13:16:13Z"
    lastUpdateTime: "2023-11-23T13:16:13Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-23T10:41:57Z"
    lastUpdateTime: "2023-11-23T13:16:13Z"
    message: ReplicaSet "nginx-deployment-6b65f48786" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
